export const OBTENER_CLIENTES='OBTENER_CLIENTES';
export const REGISTRAR_CLIENTE='REGISTRAR_CLIENTE';
export const OBTENER_CLIENTE='OBTENER_CLIENTE';
export const MODIFICAR_CLIENTE='MODIFICAR_CLIENTE';
export const ELIMINAR_CLIENTE='ELIMINAR_CLIENTE';